---
- name: Install packages for Docker
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes

- name: Install Docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: present
  become: yes

- name: Enable docker
  shell: |
    usermod -aG docker $USER
    chown $USER /var/run/docker.sock
    systemctl enable docker
  args:
    executable: /bin/bash

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
